spring:
  application:
    name: coupon #Application Name
  config:
    activate:
      on-profile: local #profile Setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
server:
  port: 8080

#spring:
#  config:
#    activate:
#      on-profile: test #profile Setting
#  datasource:
#    url: jdbc:h2:mem:test;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#server:
#  port: 8080