spring:
  application:
    name: coupon-consumer
  profiles:
    active: local

server:
  port: 8081

management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus