spring:
  application:
    name: coupon-api
  profiles:
    active: coupon
server:
  port: 7070
  tomcat:
    mbeanregistry:
      enabled: true
management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus